version: '3.9'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: "mssql+pyodbc://harvest_user:h@rvest_smwe123!@SMWECSMDEV10/Higgins_Sandbox?driver=ODBC+Driver+18+for+SQL+Server"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vintrick_mssql
    environment:
      SA_PASSWORD: "h@rvest_smwe123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

volumes:
  mssql_data: